name: relapose
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.0
  - python=3.7
  - pytorch
  - torchvision
  - visdom
  - jupyter
  - scipy  
  - matplotlib
  - opencv
  - pip
  - pip:
      - transforms3d
